# numpy exercises

#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

In [2]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

In [ ]:
zeros = np.zeros(10)
zeros

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

In [ ]:
zeros = np.zeros(10)
zeros[4] = 1
zeros

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

In [ ]:
np.arange(10,50)

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

In [ ]:
np.arange(0,9).reshape(3,3)

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

In [ ]:
nonzero = np.nonzero([1,2,0,0,4,0])
print(nonzero)

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

In [ ]:
np.eye(3,3)

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

In [ ]:
np.random.random((3,3,3))

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

In [ ]:
x = np.random.random((10,10))
print(x.min())
print(x.max())

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

In [ ]:
y = np.random.random((30))
print(y,"\n") 
print(y.mean)

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

In [ ]:
help(np.diag)

In [ ]:
np.diag([1, 2, 3, 4], k=-1)

#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

In [ ]:
z = np.random.random((5,5))
z

In [ ]:
(z-z.mean())/z.std()

#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

In [ ]:
arr1 = np.arange(10)
arr2 = np.arange(5,15)
print(arr1,arr2)
print(f"the intesect between the two arrays is: {np.intersect1d(arr1, arr2)}")

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

In [ ]:
help(np.sort)

In [ ]:
v = np.random.random(10)
np.sort(v)

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

In [ ]:
help(np.argmax)

In [ ]:
v2 = np.random.random(10)
v2

In [ ]:
maximum_value = np.argmax(v2)
maximum_value

In [ ]:
v2[8] = 0
v2

#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

In [ ]:
help(np.mean)

In [ ]:
matrix = np.arange(0,9).reshape(3,3)
matrix

In [ ]:
matrix - matrix.mean(axis = 1, keepdims = True)

#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

In [32]:
Z = np.arange(10000)
np.random.shuffle(Z)
Z.sort()
Z

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [33]:
Z[-5:]

array([9995, 9996, 9997, 9998, 9999])

In [28]:
np.argsort(Z)

array([ 639, 2259, 1415, ..., 8954, 6237, 5691], dtype=int64)

In [5]:
help(np.argsort)

Help on function argsort in module numpy:

argsort(a, axis=-1, kind=None, order=None)
    Returns the indices that would sort an array.
    
    Perform an indirect sort along the given axis using the algorithm specified
    by the `kind` keyword. It returns an array of indices of the same shape as
    `a` that index data along the given axis in sorted order.
    
    Parameters
    ----------
    a : array_like
        Array to sort.
    axis : int or None, optional
        Axis along which to sort.  The default is -1 (the last axis). If None,
        the flattened array is used.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort under the covers and, in general, the
        actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           The 'stab

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`

In [34]:
help(np.where)

Help on function where in module numpy:

where(...)
    where(condition, [x, y], /)
    
    Return elements chosen from `x` or `y` depending on `condition`.
    
    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.
    
    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.
    
    See Also
    --------
    choose
    nonzero : The function that is called when x an

In [50]:
m = np.arange(15).reshape(5,3)
m

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [52]:
np.where(m>4,m**2,m)

array([[  0,   1,   2],
       [  3,   4,  25],
       [ 36,  49,  64],
       [ 81, 100, 121],
       [144, 169, 196]])