In [1]:
# Import PyTorch and NumPy
import torch
from torch import optim
import numpy as np
list_1 = [1, 2, 3, 4]

# Create a tensor from list_a
tensor_a = torch.tensor(list_1)

# Display the tensor device
print(tensor_a.device)

# Display the tensor data type
print(tensor_a.dtype)

cpu
torch.int64


In [3]:
# Create two numpy arrays from two lists
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]

arr1 = np.array(list_1)
arr2 = np.array(list_2)
arr1, arr2

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [5]:
# Create two tensors from the arrays
tensor_a = torch.tensor(arr1)
tensor_b = torch.tensor(arr2)

# Subtract tensor_b from tensor_a 
tensor_c = tensor_a - tensor_b
print(f"tensor_c is: {tensor_c}")
      
# Multiply each element of tensor_a with each element of tensor_b
tensor_d = tensor_a * tensor_b
print(f"tensor_d is: {tensor_d}")
      
# Add tensor_c to tensor_d
tensor_e = tensor_c + tensor_d
print(f"tensor_e is: {tensor_e}")

tensor_c is: tensor([-4, -4, -4, -4], dtype=torch.int32)
tensor_d is: tensor([ 5, 12, 21, 32], dtype=torch.int32)
tensor_e is: tensor([ 1,  8, 17, 28], dtype=torch.int32)


In [7]:
import torch
import torch.nn as nn

input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])
print(f"Shape of input_tensor is: {input_tensor.shape}")

# Implement a small neural network with exactly two linear layers
model = nn.Sequential(nn.Linear(8, 4),
                      nn.Linear(4, 1)
                     )

output = model(input_tensor)
print(output)

Shape of input_tensor is: torch.Size([1, 8])
tensor([[-0.3819]], grad_fn=<AddmmBackward0>)


In [8]:
input_tensor = torch.tensor([[0.8]])

# Create a sigmoid function and apply it on input_tensor
sigmoid = nn.Sigmoid()
probability = sigmoid(input_tensor)
print(probability)

tensor([[0.6900]])


In [11]:
# Create the optimizer
optimizer = optim.SGD(model.parameters(), lr=0.001)

loss = criterion(pred, target)
loss.backward()

# Update the model's parameters using the optimizer
optimizer.step()

NameError: name 'pred' is not defined