# numpy exercises

#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

In [1]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`


In [4]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

In [5]:
zeros[4] = 1
zeros

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

In [6]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

In [8]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

In [13]:
arr = np.array([1,2,0,0,4,0])
print(arr)
print(np.nonzero(arr))

[1 2 0 0 4 0]
(array([0, 1, 4]),)


In [14]:
nonzero = np.nonzero([1,2,0,0,4,0])
print(nonzero)

(array([0, 1, 4]),)


#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

In [15]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

In [20]:
np.random.random((3,3,3))

array([[[0.98937629, 0.20342092, 0.82698854],
        [0.85681986, 0.54571577, 0.30358176],
        [0.22033421, 0.71974544, 0.56800716]],

       [[0.08071981, 0.61737491, 0.55916064],
        [0.8088959 , 0.23001693, 0.99210522],
        [0.51417816, 0.44713311, 0.3824279 ]],

       [[0.99676268, 0.31454744, 0.88657646],
        [0.26274754, 0.24776676, 0.919659  ],
        [0.70267642, 0.59235606, 0.14365789]]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

In [21]:
random_arr = np.random.random((10,10))
random_arr

array([[0.73331289, 0.01830905, 0.29951056, 0.86053683, 0.29465046,
        0.82579309, 0.12449257, 0.88417812, 0.40025647, 0.59785055],
       [0.01315386, 0.42144535, 0.98807165, 0.84915715, 0.76576966,
        0.30331555, 0.44413181, 0.75110781, 0.44636698, 0.71427633],
       [0.37062458, 0.77862912, 0.84727479, 0.24427845, 0.39061613,
        0.95935335, 0.98293791, 0.15355337, 0.98303902, 0.66553348],
       [0.05130988, 0.49715219, 0.17997733, 0.44277334, 0.90480094,
        0.22492085, 0.25198701, 0.17094654, 0.17613712, 0.97131294],
       [0.79221552, 0.86585635, 0.360262  , 0.37818623, 0.20703703,
        0.65950696, 0.24171889, 0.15810612, 0.01325391, 0.35456209],
       [0.54034702, 0.87591644, 0.43544792, 0.4607421 , 0.00610233,
        0.43949887, 0.43977026, 0.31742495, 0.07138832, 0.46065811],
       [0.94113035, 0.27867689, 0.0684681 , 0.03517937, 0.44536162,
        0.44507247, 0.28037685, 0.42983682, 0.77544761, 0.73720964],
       [0.01277589, 0.87371176, 0.6371592

In [22]:
np.max(random_arr)

np.float64(0.9880716484599424)

In [23]:
np.min(random_arr)

np.float64(0.006102327922846151)

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

In [25]:
np.random.random((30))

array([0.3012395 , 0.34512097, 0.96294964, 0.6171205 , 0.43264963,
       0.24762739, 0.28647608, 0.2803894 , 0.15045653, 0.61048957,
       0.84757174, 0.35875229, 0.40432789, 0.23785724, 0.1001155 ,
       0.93424815, 0.17515394, 0.20261157, 0.03638292, 0.50386559,
       0.39393935, 0.33378523, 0.23371621, 0.73876621, 0.31879381,
       0.24974154, 0.68578711, 0.48486481, 0.24441188, 0.35594594])

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

In [26]:
help(np.diag)

Help on _ArrayFunctionDispatcher in module numpy:

diag(v, k=0)
    Extract a diagonal or construct a diagonal array.
    
    See the more detailed documentation for ``numpy.diagonal`` if you use this
    function to extract a diagonal and wish to write to the resulting array;
    whether it returns a copy or a view depends on what version of numpy you
    are using.
    
    Parameters
    ----------
    v : array_like
        If `v` is a 2-D array, return a copy of its `k`-th diagonal.
        If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
        diagonal.
    k : int, optional
        Diagonal in question. The default is 0. Use `k>0` for diagonals
        above the main diagonal, and `k<0` for diagonals below the main
        diagonal.
    
    Returns
    -------
    out : ndarray
        The extracted diagonal or constructed diagonal array.
    
    See Also
    --------
    diagonal : Return specified diagonals.
    diagflat : Create a 2-D array with the flatt

In [29]:
random_5 = np.random.random((5,5))
random_5

array([[0.11168766, 0.60030242, 0.94874481, 0.12052103, 0.93027714],
       [0.59616548, 0.52939517, 0.70795816, 0.03540396, 0.27369818],
       [0.56287831, 0.58153441, 0.00896846, 0.52859591, 0.29494096],
       [0.15323278, 0.25382263, 0.70646327, 0.35510112, 0.99608031],
       [0.16337898, 0.96794285, 0.17996585, 0.01788008, 0.13469649]])

In [33]:
np.diag([1,2,3,4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

In [34]:
help(np.mean)

Help on _ArrayFunctionDispatcher in module numpy:

mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)
    Compute the arithmetic mean along the specified axis.
    
    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.
    
    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the means are computed. The default is to
        compute the mean of the flattened array.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a mean is performed over multiple axes,
        instead of a single axis or all the axes as before.
    dtype : data-type, optional
        Type to use in computin

In [37]:
np.random.seed(12)
z = np.random.random((5,5))
(z-z.mean(axis = 1))/z.std()

array([[-0.56612128,  0.45603596, -0.83102712,  0.10971226, -0.7712803 ],
       [ 1.74850197,  0.94241709, -1.52698326,  1.39089439, -0.40002969],
       [-0.17358529,  0.05047955,  1.23028995,  1.0754083 , -0.80856366],
       [ 0.54508795, -0.11313237, -0.15877832,  0.81929478, -0.32886571],
       [ 1.28173348, -1.72131674, -1.21883849, -1.1540824 ,  0.12274895]])

#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

In [38]:
arr1 = np.arange(10)
arr2 = np.arange(5,15)
print(arr1,arr2)
print(f"the intesect between the two arrays is: {np.intersect1d(arr1, arr2)}")

[0 1 2 3 4 5 6 7 8 9] [ 5  6  7  8  9 10 11 12 13 14]
the intesect between the two arrays is: [5 6 7 8 9]


#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

In [40]:
help(np.sort)

Help on _ArrayFunctionDispatcher in module numpy:

sort(a, axis=-1, kind=None, order=None, *, stable=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and,
        in general, the actual implementation will vary with data type.
        The 'mergesort' option is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           The 'stable' option was added.
    
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compar

In [39]:
v = np.random.random(10)
np.sort(v)

array([0.28958678, 0.32756948, 0.33464753, 0.47122978, 0.62458211,
       0.67145265, 0.70262236, 0.73312598, 0.8161683 , 0.97805808])

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

In [42]:
vector_10 = np.random.random(10)
vector_10

array([0.42405245, 0.46314887, 0.37372315, 0.4655081 , 0.03516826,
       0.08427267, 0.7325207 , 0.63619999, 0.02790779, 0.30017006])

In [43]:
np.argmax(vector_10)

np.int64(6)

#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

In [44]:
help(np.mean)

Help on _ArrayFunctionDispatcher in module numpy:

mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)
    Compute the arithmetic mean along the specified axis.
    
    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.
    
    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the means are computed. The default is to
        compute the mean of the flattened array.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a mean is performed over multiple axes,
        instead of a single axis or all the axes as before.
    dtype : data-type, optional
        Type to use in computin

In [58]:
matrix = np.arange(0,9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [59]:
matrix_mean = np.mean(matrix, axis = 1, keepdims= True)
matrix_mean

array([[1.],
       [4.],
       [7.]])

In [60]:
matrix - matrix_mean

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

In [78]:
Z = np.arange(10000)
np.random.shuffle(Z)
Z

array([8898, 5687, 3124, ..., 4454, 1125, 1458])

In [70]:
#1st Solution

In [68]:
index = np.argsort(Z)

In [69]:
sorted_indxes = index[-5:]

Z[sorted_indxes]

array([9995, 9996, 9997, 9998, 9999])

In [71]:
#2nd Solution

In [72]:
help(np.argpartition)

Help on _ArrayFunctionDispatcher in module numpy:

argpartition(a, kth, axis=-1, kind='introselect', order=None)
    Perform an indirect partition along the given axis using the
    algorithm specified by the `kind` keyword. It returns an array of
    indices of the same shape as `a` that index data along the given
    axis in partitioned order.
    
    .. versionadded:: 1.8.0
    
    Parameters
    ----------
    a : array_like
        Array to sort.
    kth : int or sequence of ints
        Element index to partition by. The k-th element will be in its
        final sorted position and all smaller elements will be moved
        before it and all larger elements behind it. The order of all
        elements in the partitions is undefined. If provided with a
        sequence of k-th it will partition all of them into their sorted
        position at once.
    
        .. deprecated:: 1.22.0
            Passing booleans as index is deprecated.
    axis : int or None, optional
        A

In [79]:
# Create an array and shuffle it
Z = np.arange(10000)
np.random.shuffle(Z)

# Number of largest values to find
n = 5

# Use np.argpartition to find the indices of the n largest values
indices = np.argpartition(Z, -n)[-n:]

# Use these indices to extract the n largest values
n_largest = Z[indices]

# If you want them sorted
n_largest_sorted = np.sort(n_largest)

print("The n largest values are (unsorted):", n_largest)
print("The n largest values are (sorted):", n_largest_sorted)

The n largest values are (unsorted): [9995 9996 9997 9998 9999]
The n largest values are (sorted): [9995 9996 9997 9998 9999]


#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`

In [86]:
random_matrix = np.arange(15).reshape(5,3)
random_matrix

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [87]:
help(np.where)

Help on _ArrayFunctionDispatcher in module numpy:

where(...)
    where(condition, [x, y], /)
    
    Return elements chosen from `x` or `y` depending on `condition`.
    
    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.
    
    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.
    
    See Also
    --------
    choose
    nonzero : The function that is called

In [88]:
np.where(random_matrix > 4, random_matrix**2, random_matrix)

array([[  0,   1,   2],
       [  3,   4,  25],
       [ 36,  49,  64],
       [ 81, 100, 121],
       [144, 169, 196]])